//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.07.04 at 01:25:18 PM EDT 
//


package br.gov.pe.gnre;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ambiente"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="1"/&gt;
 *               &lt;enumeration value="2"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="uf" type="{http://www.gnre.pe.gov.br}TUf"/&gt;
 *         &lt;element name="receita" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;http://www.gnre.pe.gov.br&gt;TReceita"&gt;
 *                 &lt;attribute name="courier" type="{http://www.gnre.pe.gov.br}TSimNao" /&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="tiposGnre" type="{http://www.gnre.pe.gov.br}TSimNao" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ambiente",
    "uf",
    "receita",
    "tiposGnre"
})
@XmlRootElement(name = "TConsultaConfigUf")
public class TConsultaConfigUf {

    @XmlElement(required = true)
    protected String ambiente;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected TUf uf;
    protected TConsultaConfigUf.Receita receita;
    @XmlSchemaType(name = "string")
    protected TSimNao tiposGnre;

    /**
     * Gets the value of the ambiente property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAmbiente() {
        return ambiente;
    }

    /**
     * Sets the value of the ambiente property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAmbiente(String value) {
        this.ambiente = value;
    }

    /**
     * Gets the value of the uf property.
     * 
     * @return
     *     possible object is
     *     {@link TUf }
     *     
     */
    public TUf getUf() {
        return uf;
    }

    /**
     * Sets the value of the uf property.
     * 
     * @param value
     *     allowed object is
     *     {@link TUf }
     *     
     */
    public void setUf(TUf value) {
        this.uf = value;
    }

    /**
     * Gets the value of the receita property.
     * 
     * @return
     *     possible object is
     *     {@link TConsultaConfigUf.Receita }
     *     
     */
    public TConsultaConfigUf.Receita getReceita() {
        return receita;
    }

    /**
     * Sets the value of the receita property.
     * 
     * @param value
     *     allowed object is
     *     {@link TConsultaConfigUf.Receita }
     *     
     */
    public void setReceita(TConsultaConfigUf.Receita value) {
        this.receita = value;
    }

    /**
     * Gets the value of the tiposGnre property.
     * 
     * @return
     *     possible object is
     *     {@link TSimNao }
     *     
     */
    public TSimNao getTiposGnre() {
        return tiposGnre;
    }

    /**
     * Sets the value of the tiposGnre property.
     * 
     * @param value
     *     allowed object is
     *     {@link TSimNao }
     *     
     */
    public void setTiposGnre(TSimNao value) {
        this.tiposGnre = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;simpleContent&gt;
     *     &lt;extension base="&lt;http://www.gnre.pe.gov.br&gt;TReceita"&gt;
     *       &lt;attribute name="courier" type="{http://www.gnre.pe.gov.br}TSimNao" /&gt;
     *     &lt;/extension&gt;
     *   &lt;/simpleContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Receita {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "courier")
        protected TSimNao courier;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the courier property.
         * 
         * @return
         *     possible object is
         *     {@link TSimNao }
         *     
         */
        public TSimNao getCourier() {
            return courier;
        }

        /**
         * Sets the value of the courier property.
         * 
         * @param value
         *     allowed object is
         *     {@link TSimNao }
         *     
         */
        public void setCourier(TSimNao value) {
            this.courier = value;
        }

    }

}
