//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.07.04 at 01:01:40 PM EDT 
//


package br.com.projectSpringForTest.GNRE.retornoConsultaConfig;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the br.gov.pe.gnre package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: br.gov.pe.gnre
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TConfigUf }
     * 
     */
    public TConfigUf createTConfigUf() {
        return new TConfigUf();
    }

    /**
     * Create an instance of {@link TConfigUf.Receitas }
     * 
     */
    public TConfigUf.Receitas createTConfigUfReceitas() {
        return new TConfigUf.Receitas();
    }

    /**
     * Create an instance of {@link TConfigUf.Receitas.Receita }
     * 
     */
    public TConfigUf.Receitas.Receita createTConfigUfReceitasReceita() {
        return new TConfigUf.Receitas.Receita();
    }

    /**
     * Create an instance of {@link TConfigUf.Receitas.Receita.CamposAdicionais }
     * 
     */
    public TConfigUf.Receitas.Receita.CamposAdicionais createTConfigUfReceitasReceitaCamposAdicionais() {
        return new TConfigUf.Receitas.Receita.CamposAdicionais();
    }

    /**
     * Create an instance of {@link TConfigUf.Receitas.Receita.CamposAdicionais.CampoAdicional }
     * 
     */
    public TConfigUf.Receitas.Receita.CamposAdicionais.CampoAdicional createTConfigUfReceitasReceitaCamposAdicionaisCampoAdicional() {
        return new TConfigUf.Receitas.Receita.CamposAdicionais.CampoAdicional();
    }

    /**
     * Create an instance of {@link TConfigUf.Receitas.Receita.TiposDocumentosOrigem }
     * 
     */
    public TConfigUf.Receitas.Receita.TiposDocumentosOrigem createTConfigUfReceitasReceitaTiposDocumentosOrigem() {
        return new TConfigUf.Receitas.Receita.TiposDocumentosOrigem();
    }

    /**
     * Create an instance of {@link TConfigUf.Receitas.Receita.PeriodosApuracao }
     * 
     */
    public TConfigUf.Receitas.Receita.PeriodosApuracao createTConfigUfReceitasReceitaPeriodosApuracao() {
        return new TConfigUf.Receitas.Receita.PeriodosApuracao();
    }

    /**
     * Create an instance of {@link TConfigUf.Receitas.Receita.Produtos }
     * 
     */
    public TConfigUf.Receitas.Receita.Produtos createTConfigUfReceitasReceitaProdutos() {
        return new TConfigUf.Receitas.Receita.Produtos();
    }

    /**
     * Create an instance of {@link TConfigUf.Receitas.Receita.DetalhamentosReceita }
     * 
     */
    public TConfigUf.Receitas.Receita.DetalhamentosReceita createTConfigUfReceitasReceitaDetalhamentosReceita() {
        return new TConfigUf.Receitas.Receita.DetalhamentosReceita();
    }

    /**
     * Create an instance of {@link TConfigUf.SituacaoConsulta }
     * 
     */
    public TConfigUf.SituacaoConsulta createTConfigUfSituacaoConsulta() {
        return new TConfigUf.SituacaoConsulta();
    }

    /**
     * Create an instance of {@link TConfigUf.ExigeUfFavorecida }
     * 
     */
    public TConfigUf.ExigeUfFavorecida createTConfigUfExigeUfFavorecida() {
        return new TConfigUf.ExigeUfFavorecida();
    }

    /**
     * Create an instance of {@link TConfigUf.ExigeReceita }
     * 
     */
    public TConfigUf.ExigeReceita createTConfigUfExigeReceita() {
        return new TConfigUf.ExigeReceita();
    }

    /**
     * Create an instance of {@link TConfigUf.VersoesXml }
     * 
     */
    public TConfigUf.VersoesXml createTConfigUfVersoesXml() {
        return new TConfigUf.VersoesXml();
    }

    /**
     * Create an instance of {@link TConfigUf.QtdMaximas }
     * 
     */
    public TConfigUf.QtdMaximas createTConfigUfQtdMaximas() {
        return new TConfigUf.QtdMaximas();
    }

    /**
     * Create an instance of {@link TConfigUf.TiposGnreDaUF }
     * 
     */
    public TConfigUf.TiposGnreDaUF createTConfigUfTiposGnreDaUF() {
        return new TConfigUf.TiposGnreDaUF();
    }

    /**
     * Create an instance of {@link TIdentificacao2 }
     * 
     */
    public TIdentificacao2 createTIdentificacao2() {
        return new TIdentificacao2();
    }

    /**
     * Create an instance of {@link TConfigUf.Receitas.Receita.ExigeDetalhamentoReceita }
     * 
     */
    public TConfigUf.Receitas.Receita.ExigeDetalhamentoReceita createTConfigUfReceitasReceitaExigeDetalhamentoReceita() {
        return new TConfigUf.Receitas.Receita.ExigeDetalhamentoReceita();
    }

    /**
     * Create an instance of {@link TConfigUf.Receitas.Receita.ExigeProduto }
     * 
     */
    public TConfigUf.Receitas.Receita.ExigeProduto createTConfigUfReceitasReceitaExigeProduto() {
        return new TConfigUf.Receitas.Receita.ExigeProduto();
    }

    /**
     * Create an instance of {@link TConfigUf.Receitas.Receita.ExigePeriodoReferencia }
     * 
     */
    public TConfigUf.Receitas.Receita.ExigePeriodoReferencia createTConfigUfReceitasReceitaExigePeriodoReferencia() {
        return new TConfigUf.Receitas.Receita.ExigePeriodoReferencia();
    }

    /**
     * Create an instance of {@link TConfigUf.Receitas.Receita.ExigePeriodoApuracao }
     * 
     */
    public TConfigUf.Receitas.Receita.ExigePeriodoApuracao createTConfigUfReceitasReceitaExigePeriodoApuracao() {
        return new TConfigUf.Receitas.Receita.ExigePeriodoApuracao();
    }

    /**
     * Create an instance of {@link TConfigUf.Receitas.Receita.ExigeParcela }
     * 
     */
    public TConfigUf.Receitas.Receita.ExigeParcela createTConfigUfReceitasReceitaExigeParcela() {
        return new TConfigUf.Receitas.Receita.ExigeParcela();
    }

    /**
     * Create an instance of {@link TConfigUf.Receitas.Receita.ValorExigido }
     * 
     */
    public TConfigUf.Receitas.Receita.ValorExigido createTConfigUfReceitasReceitaValorExigido() {
        return new TConfigUf.Receitas.Receita.ValorExigido();
    }

    /**
     * Create an instance of {@link TConfigUf.Receitas.Receita.ExigeDocumentoOrigem }
     * 
     */
    public TConfigUf.Receitas.Receita.ExigeDocumentoOrigem createTConfigUfReceitasReceitaExigeDocumentoOrigem() {
        return new TConfigUf.Receitas.Receita.ExigeDocumentoOrigem();
    }

    /**
     * Create an instance of {@link TConfigUf.Receitas.Receita.VersoesXmlDocOrigem }
     * 
     */
    public TConfigUf.Receitas.Receita.VersoesXmlDocOrigem createTConfigUfReceitasReceitaVersoesXmlDocOrigem() {
        return new TConfigUf.Receitas.Receita.VersoesXmlDocOrigem();
    }

    /**
     * Create an instance of {@link TConfigUf.Receitas.Receita.ExigeDataVencimento }
     * 
     */
    public TConfigUf.Receitas.Receita.ExigeDataVencimento createTConfigUfReceitasReceitaExigeDataVencimento() {
        return new TConfigUf.Receitas.Receita.ExigeDataVencimento();
    }

    /**
     * Create an instance of {@link TConfigUf.Receitas.Receita.ExigeDataPagamento }
     * 
     */
    public TConfigUf.Receitas.Receita.ExigeDataPagamento createTConfigUfReceitasReceitaExigeDataPagamento() {
        return new TConfigUf.Receitas.Receita.ExigeDataPagamento();
    }

    /**
     * Create an instance of {@link TConfigUf.Receitas.Receita.ExigeConvenio }
     * 
     */
    public TConfigUf.Receitas.Receita.ExigeConvenio createTConfigUfReceitasReceitaExigeConvenio() {
        return new TConfigUf.Receitas.Receita.ExigeConvenio();
    }

    /**
     * Create an instance of {@link TConfigUf.Receitas.Receita.ExigeValorFecp }
     * 
     */
    public TConfigUf.Receitas.Receita.ExigeValorFecp createTConfigUfReceitasReceitaExigeValorFecp() {
        return new TConfigUf.Receitas.Receita.ExigeValorFecp();
    }

    /**
     * Create an instance of {@link TConfigUf.Receitas.Receita.ExigeCamposAdicionais }
     * 
     */
    public TConfigUf.Receitas.Receita.ExigeCamposAdicionais createTConfigUfReceitasReceitaExigeCamposAdicionais() {
        return new TConfigUf.Receitas.Receita.ExigeCamposAdicionais();
    }

    /**
     * Create an instance of {@link TConfigUf.Receitas.Receita.TiposGnre }
     * 
     */
    public TConfigUf.Receitas.Receita.TiposGnre createTConfigUfReceitasReceitaTiposGnre() {
        return new TConfigUf.Receitas.Receita.TiposGnre();
    }

    /**
     * Create an instance of {@link TConfigUf.Receitas.Receita.CamposAdicionais.CampoAdicional.Codigo }
     * 
     */
    public TConfigUf.Receitas.Receita.CamposAdicionais.CampoAdicional.Codigo createTConfigUfReceitasReceitaCamposAdicionaisCampoAdicionalCodigo() {
        return new TConfigUf.Receitas.Receita.CamposAdicionais.CampoAdicional.Codigo();
    }

    /**
     * Create an instance of {@link TConfigUf.Receitas.Receita.CamposAdicionais.CampoAdicional.Tipo }
     * 
     */
    public TConfigUf.Receitas.Receita.CamposAdicionais.CampoAdicional.Tipo createTConfigUfReceitasReceitaCamposAdicionaisCampoAdicionalTipo() {
        return new TConfigUf.Receitas.Receita.CamposAdicionais.CampoAdicional.Tipo();
    }

    /**
     * Create an instance of {@link TConfigUf.Receitas.Receita.CamposAdicionais.CampoAdicional.VersoesXmlCampoAdicional }
     * 
     */
    public TConfigUf.Receitas.Receita.CamposAdicionais.CampoAdicional.VersoesXmlCampoAdicional createTConfigUfReceitasReceitaCamposAdicionaisCampoAdicionalVersoesXmlCampoAdicional() {
        return new TConfigUf.Receitas.Receita.CamposAdicionais.CampoAdicional.VersoesXmlCampoAdicional();
    }

    /**
     * Create an instance of {@link TConfigUf.Receitas.Receita.TiposDocumentosOrigem.TipoDocumentoOrigem }
     * 
     */
    public TConfigUf.Receitas.Receita.TiposDocumentosOrigem.TipoDocumentoOrigem createTConfigUfReceitasReceitaTiposDocumentosOrigemTipoDocumentoOrigem() {
        return new TConfigUf.Receitas.Receita.TiposDocumentosOrigem.TipoDocumentoOrigem();
    }

    /**
     * Create an instance of {@link TConfigUf.Receitas.Receita.PeriodosApuracao.PeriodoApuracao }
     * 
     */
    public TConfigUf.Receitas.Receita.PeriodosApuracao.PeriodoApuracao createTConfigUfReceitasReceitaPeriodosApuracaoPeriodoApuracao() {
        return new TConfigUf.Receitas.Receita.PeriodosApuracao.PeriodoApuracao();
    }

    /**
     * Create an instance of {@link TConfigUf.Receitas.Receita.Produtos.Produto }
     * 
     */
    public TConfigUf.Receitas.Receita.Produtos.Produto createTConfigUfReceitasReceitaProdutosProduto() {
        return new TConfigUf.Receitas.Receita.Produtos.Produto();
    }

    /**
     * Create an instance of {@link TConfigUf.Receitas.Receita.DetalhamentosReceita.DetalhamentoReceita }
     * 
     */
    public TConfigUf.Receitas.Receita.DetalhamentosReceita.DetalhamentoReceita createTConfigUfReceitasReceitaDetalhamentosReceitaDetalhamentoReceita() {
        return new TConfigUf.Receitas.Receita.DetalhamentosReceita.DetalhamentoReceita();
    }

}
