//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.07.04 at 01:01:40 PM EDT 
//


package br.com.projectSpringForTest.GNRE.retornoConsultaConfig;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TCamposGNRE.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TCamposGNRE"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;whiteSpace value="preserve"/&gt;
 *     &lt;enumeration value="c01_UfFavorecida"/&gt;
 *     &lt;enumeration value="c02_receita"/&gt;
 *     &lt;enumeration value="c25_detalhamentoReceita"/&gt;
 *     &lt;enumeration value="c26_produto"/&gt;
 *     &lt;enumeration value="c27_tipoIdentificacaoEmitente"/&gt;
 *     &lt;enumeration value="c03_idContribuinteEmitente"/&gt;
 *     &lt;enumeration value="c28_tipoDocOrigem"/&gt;
 *     &lt;enumeration value="c04_docOrigem"/&gt;
 *     &lt;enumeration value="c06_valorPrincipal"/&gt;
 *     &lt;enumeration value="c07_atualizacaoMonetaria"/&gt;
 *     &lt;enumeration value="c08_juros"/&gt;
 *     &lt;enumeration value="c09_multa"/&gt;
 *     &lt;enumeration value="c10_valorTotal"/&gt;
 *     &lt;enumeration value="c14_dataVencimento"/&gt;
 *     &lt;enumeration value="c33_dataPagamento"/&gt;
 *     &lt;enumeration value="c29_dataLimitePagamento"/&gt;
 *     &lt;enumeration value="c15_convenio"/&gt;
 *     &lt;enumeration value="c16_razaoSocialEmitente"/&gt;
 *     &lt;enumeration value="c17_inscricaoEstadualEmitente"/&gt;
 *     &lt;enumeration value="c18_enderecoEmitente"/&gt;
 *     &lt;enumeration value="c19_municipioEmitente"/&gt;
 *     &lt;enumeration value="c20_ufEnderecoEmitente"/&gt;
 *     &lt;enumeration value="c21_cepEmitente"/&gt;
 *     &lt;enumeration value="c22_telefoneEmitente"/&gt;
 *     &lt;enumeration value="c34_tipoIdentificacaoDestinatario"/&gt;
 *     &lt;enumeration value="c35_idContribuinteDestinatario"/&gt;
 *     &lt;enumeration value="c36_inscricaoEstadualDestinatario"/&gt;
 *     &lt;enumeration value="c37_razaoSocialDestinatario"/&gt;
 *     &lt;enumeration value="c38_municipioDestinatario"/&gt;
 *     &lt;enumeration value="c30_nossoNumero"/&gt;
 *     &lt;enumeration value="c05_referencia"/&gt;
 *     &lt;enumeration value="ufFavorecida"/&gt;
 *     &lt;enumeration value="receita"/&gt;
 *     &lt;enumeration value="detalhamentoReceita"/&gt;
 *     &lt;enumeration value="periodo"/&gt;
 *     &lt;enumeration value="produto"/&gt;
 *     &lt;enumeration value="referencia"/&gt;
 *     &lt;enumeration value="mes"/&gt;
 *     &lt;enumeration value="ano"/&gt;
 *     &lt;enumeration value="parcela"/&gt;
 *     &lt;enumeration value="documentoOrigem"/&gt;
 *     &lt;enumeration value="dataVencimento"/&gt;
 *     &lt;enumeration value="dataPagamento"/&gt;
 *     &lt;enumeration value="convenio"/&gt;
 *     &lt;enumeration value="camposExtras"/&gt;
 *     &lt;enumeration value="c39_campoExtra1"/&gt;
 *     &lt;enumeration value="c40_campoExtra2"/&gt;
 *     &lt;enumeration value="c41_campoExtra3"/&gt;
 *     &lt;enumeration value="c39_camposExtras"/&gt;
 *     &lt;enumeration value="campoExtra"/&gt;
 *     &lt;enumeration value="codigo"/&gt;
 *     &lt;enumeration value="tipo"/&gt;
 *     &lt;enumeration value="valor"/&gt;
 *     &lt;enumeration value="c42_identificadorGuia"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "TCamposGNRE")
@XmlEnum
public enum TCamposGNRE {

    @XmlEnumValue("c01_UfFavorecida")
    C_01_UF_FAVORECIDA("c01_UfFavorecida"),
    @XmlEnumValue("c02_receita")
    C_02_RECEITA("c02_receita"),
    @XmlEnumValue("c25_detalhamentoReceita")
    C_25_DETALHAMENTO_RECEITA("c25_detalhamentoReceita"),
    @XmlEnumValue("c26_produto")
    C_26_PRODUTO("c26_produto"),
    @XmlEnumValue("c27_tipoIdentificacaoEmitente")
    C_27_TIPO_IDENTIFICACAO_EMITENTE("c27_tipoIdentificacaoEmitente"),
    @XmlEnumValue("c03_idContribuinteEmitente")
    C_03_ID_CONTRIBUINTE_EMITENTE("c03_idContribuinteEmitente"),
    @XmlEnumValue("c28_tipoDocOrigem")
    C_28_TIPO_DOC_ORIGEM("c28_tipoDocOrigem"),
    @XmlEnumValue("c04_docOrigem")
    C_04_DOC_ORIGEM("c04_docOrigem"),
    @XmlEnumValue("c06_valorPrincipal")
    C_06_VALOR_PRINCIPAL("c06_valorPrincipal"),
    @XmlEnumValue("c07_atualizacaoMonetaria")
    C_07_ATUALIZACAO_MONETARIA("c07_atualizacaoMonetaria"),
    @XmlEnumValue("c08_juros")
    C_08_JUROS("c08_juros"),
    @XmlEnumValue("c09_multa")
    C_09_MULTA("c09_multa"),
    @XmlEnumValue("c10_valorTotal")
    C_10_VALOR_TOTAL("c10_valorTotal"),
    @XmlEnumValue("c14_dataVencimento")
    C_14_DATA_VENCIMENTO("c14_dataVencimento"),
    @XmlEnumValue("c33_dataPagamento")
    C_33_DATA_PAGAMENTO("c33_dataPagamento"),
    @XmlEnumValue("c29_dataLimitePagamento")
    C_29_DATA_LIMITE_PAGAMENTO("c29_dataLimitePagamento"),
    @XmlEnumValue("c15_convenio")
    C_15_CONVENIO("c15_convenio"),
    @XmlEnumValue("c16_razaoSocialEmitente")
    C_16_RAZAO_SOCIAL_EMITENTE("c16_razaoSocialEmitente"),
    @XmlEnumValue("c17_inscricaoEstadualEmitente")
    C_17_INSCRICAO_ESTADUAL_EMITENTE("c17_inscricaoEstadualEmitente"),
    @XmlEnumValue("c18_enderecoEmitente")
    C_18_ENDERECO_EMITENTE("c18_enderecoEmitente"),
    @XmlEnumValue("c19_municipioEmitente")
    C_19_MUNICIPIO_EMITENTE("c19_municipioEmitente"),
    @XmlEnumValue("c20_ufEnderecoEmitente")
    C_20_UF_ENDERECO_EMITENTE("c20_ufEnderecoEmitente"),
    @XmlEnumValue("c21_cepEmitente")
    C_21_CEP_EMITENTE("c21_cepEmitente"),
    @XmlEnumValue("c22_telefoneEmitente")
    C_22_TELEFONE_EMITENTE("c22_telefoneEmitente"),
    @XmlEnumValue("c34_tipoIdentificacaoDestinatario")
    C_34_TIPO_IDENTIFICACAO_DESTINATARIO("c34_tipoIdentificacaoDestinatario"),
    @XmlEnumValue("c35_idContribuinteDestinatario")
    C_35_ID_CONTRIBUINTE_DESTINATARIO("c35_idContribuinteDestinatario"),
    @XmlEnumValue("c36_inscricaoEstadualDestinatario")
    C_36_INSCRICAO_ESTADUAL_DESTINATARIO("c36_inscricaoEstadualDestinatario"),
    @XmlEnumValue("c37_razaoSocialDestinatario")
    C_37_RAZAO_SOCIAL_DESTINATARIO("c37_razaoSocialDestinatario"),
    @XmlEnumValue("c38_municipioDestinatario")
    C_38_MUNICIPIO_DESTINATARIO("c38_municipioDestinatario"),
    @XmlEnumValue("c30_nossoNumero")
    C_30_NOSSO_NUMERO("c30_nossoNumero"),
    @XmlEnumValue("c05_referencia")
    C_05_REFERENCIA("c05_referencia"),
    @XmlEnumValue("ufFavorecida")
    UF_FAVORECIDA("ufFavorecida"),
    @XmlEnumValue("receita")
    RECEITA("receita"),
    @XmlEnumValue("detalhamentoReceita")
    DETALHAMENTO_RECEITA("detalhamentoReceita"),
    @XmlEnumValue("periodo")
    PERIODO("periodo"),
    @XmlEnumValue("produto")
    PRODUTO("produto"),
    @XmlEnumValue("referencia")
    REFERENCIA("referencia"),
    @XmlEnumValue("mes")
    MES("mes"),
    @XmlEnumValue("ano")
    ANO("ano"),
    @XmlEnumValue("parcela")
    PARCELA("parcela"),
    @XmlEnumValue("documentoOrigem")
    DOCUMENTO_ORIGEM("documentoOrigem"),
    @XmlEnumValue("dataVencimento")
    DATA_VENCIMENTO("dataVencimento"),
    @XmlEnumValue("dataPagamento")
    DATA_PAGAMENTO("dataPagamento"),
    @XmlEnumValue("convenio")
    CONVENIO("convenio"),
    @XmlEnumValue("camposExtras")
    CAMPOS_EXTRAS("camposExtras"),
    @XmlEnumValue("c39_campoExtra1")
    C_39_CAMPO_EXTRA_1("c39_campoExtra1"),
    @XmlEnumValue("c40_campoExtra2")
    C_40_CAMPO_EXTRA_2("c40_campoExtra2"),
    @XmlEnumValue("c41_campoExtra3")
    C_41_CAMPO_EXTRA_3("c41_campoExtra3"),
    @XmlEnumValue("c39_camposExtras")
    C_39_CAMPOS_EXTRAS("c39_camposExtras"),
    @XmlEnumValue("campoExtra")
    CAMPO_EXTRA("campoExtra"),
    @XmlEnumValue("codigo")
    CODIGO("codigo"),
    @XmlEnumValue("tipo")
    TIPO("tipo"),
    @XmlEnumValue("valor")
    VALOR("valor"),
    @XmlEnumValue("c42_identificadorGuia")
    C_42_IDENTIFICADOR_GUIA("c42_identificadorGuia");
    private final String value;

    TCamposGNRE(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TCamposGNRE fromValue(String v) {
        for (TCamposGNRE c: TCamposGNRE.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
